### ISSUE TITLE
Module ports beyond io

### ISSUE THREAD

**Issue by grebe** [ucb-bar/chisel3#101]
It is my understanding that firrtl doesn't care what input and output ports of a module are named. The current chisel3 frontend has a private variable called ports that is only clk, reset, and io. 

I propose that we make this variable protected instead of private.

This will allow people to have input/output ports outside of the IO bundle, making chisel3 match firrtl more closely.

**Comment by aswaterman** [comment]
Depending on the use case, #156 and/or #157 may satisfy the demand.

**Comment by chick** [comment]
@grebe should this be open at this point

**Comment by ducky64** [comment]
Discussion should continue in #469 and #427
