### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by schoeberl** [ucb-bar/chisel3#103]
What is the correct setting in build.sbt to use the local published version of Chisel 3? I tried to set it similar to Chisel 2:

libraryDependencies += "edu.berkeley.cs" %% "chisel" % "3.0-SNAPSHOT"

But got:
	Note: Unresolved dependencies path:
[warn] 		edu.berkeley.cs:chisel_2.11:3.0-SNAPSHOT

**Comment by ucbjrl** [comment]
On Feb 22, 2016, at 11:43 AM, Martin Schoeberl <notifications@github.com> wrote:

> What is the correct setting in build.sbt to use the local published version of Chisel 3? I tried to set it similar to Chisel 2:
> 
> libraryDependencies += "edu.berkeley.cs" %% "chisel" % "3.0-SNAPSHOT"
> 
> But got:
> Note: Unresolved dependencies path:
> [warn] edu.berkeley.cs:chisel_2.11:3.0-SNAPSHOT
> 
> �
> Reply to this email directly or view it on GitHub.
> 

Check the �version� line in chisel3/build.sbt.

It�s currently:

    version := �3.0"

so your library dependencies should be:

    libraryDependencies += "edu.berkeley.cs" %% "chisel" % �3.0�

**Comment by schoeberl** [comment]
Thanks! that fixed it. Maybe add this to the README.

BTW: You're having non-ASCII quotation marks (single and double) in your email, which end up as non-printable characters (in my view) in Mail and Firefox.

**Comment by ucbjrl** [comment]
Closed by #133
