### ISSUE TITLE
Chisel errors should suggest a resolution.

### ISSUE THREAD

**Issue by ducky64** [ucb-bar/chisel3#13]
Example: "Parameterized Bundle class (blah) needs cloneType method. You are probably using an anonymous Bundle object that captures external state and hence is un-cloneTypeable in class (blah)"

It does a good job telling me very specifically what the error is, but doesn't suggest a resolution strategy. Should the Bundle not be a nested class? Does it just need to have a cloneType overloaded?

**Comment by aswaterman** [comment]
The general issue still stands.  I'd suggest making issues or PRs against specific error messages.  In this case, the message does suggest a resolution strategy, but with the wrong verb (instead of "x needs cloneType," change to "add cloneType to x").
