### ISSUE TITLE
Arbiter family of apply methods use (gen: T, n: Int) signature

### ISSUE THREAD

**Issue by chick** [ucb-bar/chisel3#138]
Possible minor consistency issue. While most things aggregate or aggregate like, in chisel3, use the signature
The following Arbiter, RRArbiter, ArbiterIO,QueueIO, use the older form.
(n:Int, gen: T), with the flipped argument version deprecated or removed.  
It could be that these are not worth changing, but it would be an easy fix I could make to provide new apply methods and deprecate the older forms

**Comment by aswaterman** [comment]
We need to provide backwards compatibility, so I propose a companion object
approach to construction.  object Arbiter can take both argument orders.
The class constructor can continue to take the old order.

Starting to wonder if swapping the argument orders is more trouble than it
is worth...
