### ISSUE TITLE
Bulk connects override bundle components even without valid assignment (different than Chisel2)

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/chisel3#159]
This code behaves differently in Chisel2 and 3

```
io.rocc.resp.ready := !(wb_reg_valid && wb_ctrl.wxd)
...
csr.io.rocc <> io.rocc
```

In Chisel2 because the csr module does not write to rocc.resp.ready the initial assignment is preserved and last connect semantics are ignored.

In Chisel3 last connect semantics are honored and the second bulk connect overrides the previous assignment. This leads to a random value since csr.io.rocc.resp.ready was never written to.

This anomalous behavior in Chisel2 can cause issues in porting from chisel2 to chisel3 as it silently generates a different circuit.

**Comment by aswaterman** [comment]
I think this should be filed as a ticket against chisel2 because not detecting it is a limitation of the compatibility checker
