### ISSUE TITLE
Native Windows Support

### ISSUE THREAD

**Issue by sirinath** [ucb-bar/chisel3#161]
Can you support windows as a 1st class citizen in the stack?

**Comment by aswaterman** [comment]
No.  The core of Chisel is written entirely in Scala, so it should be usable in any system with a JVM, including Windows.  But beyond that, we have no plans to devote resources to Windows development.  In particular, most people will find hacking on the Chisel internals impossible without a Unix-like environment.

As always, we are happy to accept patches that fix compatibility problems.
