### ISSUE TITLE
Separation of Utils and Frontend

### ISSUE THREAD

**Issue by ducky64** [ucb-bar/chisel3#164]
With macro-based source locators happening ( #147 ), there now needs to be a clean separation of the Chisel frontend (core data types - Bool, UInt, etc) and things which invoke the frontend (like utils - Mux, Cat, PopCount, and friends) because macros require definition and invocation to be in different compilation units.

I think it makes sense for Chisel utils be strictly dependent on Chisel frontend since it provides an example of how libraries can be written and structured (rather than invoking Chisel frontend internal functions directly, bypassing the source locator macro layer). If necessary, utils can also have transform macros for source locators, and may demonstrate multiple levels of source locators.

Anyways, the current problematic calls I've found are:
- `Data.toBits` is dependent on `Cat`
- `Vec.count` is dependent on `PopCount`
- `Vec.{indexWhere, lastIndexWhere}` are dependent on `PriorityMux`
- `Vec.onlyIndexWhere` is dependent on `Mux1H`

This issue was brought up about a year ago, during the Chisel3 code review, but that was before separate compilation needed to happen, so the consensus then was to leave it as-is. That's not necessarily a good option anymore. Thoughts for solving this?

**Comment by aswaterman** [comment]
@ducky64 I think it's fair to reverse some of these dependencies... let me look into it.

**Comment by aswaterman** [comment]
Can Chisel.util depend on something that's private[Chisel]?  Or is there some way of making stuff visible to Chisel.util but not to users of Chisel?  I'm thinking the easiest thing to do is to move the implementations into an object that lives in Chisel, and have e.g. both Vec.count and PopCount call SeqUtils.count:

    private[Chisel] object SeqUtils {
      def toUInt[T <: Data](x: Seq[T]): UInt                   
      def count(x: Seq[Bool]): UInt 
      def prioirityMux[T <: Data](cond: Seq[Bool], value: Seq[T]): T  
      def oneHotMux[T <: Data](cond: Seq[Bool], value: Seq[T]): T     
    }

**Comment by sdtwigg** [comment]
@aswaterman Yes, subpackages can view parent package private values.

**Comment by aswaterman** [comment]
Ok I'll make a PR

**Comment by aswaterman** [comment]
@ducky64 anything else that f9dd3feae5727424b85b18cd6064140403b0411b doesn't handle?

**Comment by ducky64** [comment]
From #168, looks like a sufficient split. Since SeqUtils will be placed in Chisel frontend, it will also have to be written without the nice source locator macros (so instead of toBits, it would be do_toBits, and their type signatures would take an explicit source locator parameter)
