### ISSUE TITLE
Different sementics for Vec(n, type) and Vec.fill(n)(type)?

### ISSUE THREAD

**Issue by donggyukim** [ucb-bar/chisel3#165]
Should we expect those two have different semantics in Chisel3? For example, `Reg(Vec(n, UInt(width=w))` works, but `Reg(Vec.fill(n)(UInt(width=w))` is broken.

**Comment by aswaterman** [comment]
Vec.fill creates a value (i.e., a Wire), whereas the Vec.apply creates a type.  This is different from chisel2, where they were basically the same.
