### ISSUE TITLE
VecLike.read, write is deprecated but not so in Mem

### ISSUE THREAD

**Issue by ducky64** [ucb-bar/chisel3#189]
Mem extends VecLike. What's the plan here? It seems like apply can take care of the non-masked read/write, so are those planned to be deprecated? Or is the plan to retain Mem.read and Mem.write but eliminate those from Vec/VecLike?

(this has implications for source locator implementation for Mem, because of the inheritance of .read and .write)

**Comment by aswaterman** [comment]
I think remove them from Vec/VecLike and keep them for Mem.

**Comment by sdtwigg** [comment]
Mem extending VecLike is perhaps a bit 'odd'. VecLike extends IndexedSeq. IndexedSeq has many operations (some subtle, like toString) that will iterate through the entire memory, generating a port for each address.... This is particularly bad because Mem won't cache any of those port creations.

**Comment by ducky64** [comment]
Resolution: try to make Mem not extend VecLike and hope all the chisel3 based code doesn't immediately catch fire.
Might keep current behavior in compatibility mode. Might also keep some IndexedSeq operations,
