### ISSUE TITLE
Publish Chisel3 sbt subprojects in a single jar

### ISSUE THREAD

**Issue by ucbjrl** [ucb-bar/chisel3#208]
We'd like to publish all Chisel3 sbt subprojects in a single jar. It appeared that the initial attempt at this was working, but it was probably masked by the fact that the separately published jars were still around.
See #194

**Comment by ducky64** [comment]
This seems to be the case now.

**Comment by ucbjrl** [comment]
I disagree. We're still publishing 3 separate jars: coremacros,
chiselfrontend, and chisel3 with sbt 013.11

**Comment by ducky64** [comment]
The projects are being published separately, but it seems chisel3 includes everything that is in chiselfrontend and coremacros

**Comment by ucbjrl** [comment]
The issue should be updated to "avoid publishing the coremacros and
chiselFrontend jars" since these no longer seem to be required.

**Comment by ducky64** [comment]
Hopefully this issue is _actually_ resolved now.
