### ISSUE TITLE
Chisel3 build.sbt breaks Rocket-Chip build

### ISSUE THREAD

**Issue by zhemao** [ucb-bar/chisel3#213]
I upgraded chisel3 to master recently and got an sbt failure.

    /scratch/zhemao/rocket-chip/chisel3/build.sbt:109: error: reference to chiselFrontend is ambiguous;
    it is imported twice in the same scope by
    import BuildSettings._
    and import $6904c9bb540ccc2f8aba._
    publish <<= (publish) dependsOn (publish in coreMacros, publish in chiselFrontend)

I did a git bisect and the commit that caused the failure is the following.

https://github.com/ucb-bar/chisel3/commit/70271cd8c3811cb518e81d1d5eb3ed20cb1e2063

SBT doesn't seem to like this hack at all.

@chick

**Comment by aswaterman** [comment]
This is probably my fault... I added the chiselMacros and chiselFrontend dependencies to rocket-chip, but rocket-chip shouldn't even know about them.  So @chick's fix is doing us a favor.

I'm making a rocket-chip PR that fixes this.
