### ISSUE TITLE
MuxCase and MuxLookup only take Bits subclasses, not Data subclasses?

### ISSUE THREAD

**Issue by zhemao** [ucb-bar/chisel3#214]
Is there a reason MuxCase and MuxLookup can only take subclasses of Bits? It would be useful to also be able to call it for bundles. I tried making the change myself (just changing the type parameters in the definition) and it works just fine. I don't see why they shouldn't be able to take the same set of types as the regular Mux builtin.

**Comment by aswaterman** [comment]
I agree, can you make the corresponding PR?

**Comment by zhemao** [comment]
Sure, I'll do that.
