### ISSUE TITLE
SeqMem address register not initialized

### ISSUE THREAD

**Issue by zhemao** [ucb-bar/chisel3#216]
We're running into an annoying Chisel issue that's breaking one of the ground tests in VCS. Basically, the problem is that the address register SeqMem (GEN_48 in the following screenshot) is not initialized. This causes one of the memory cells (seq_plru_state[7]) to get overwritten with Xs during reset.

![seqmem-bug-report](https://cloud.githubusercontent.com/assets/433799/15916823/58484540-2dab-11e6-9dcc-d72b15e9fd8d.png)

**Comment by aswaterman** [comment]
You should open a FIRRTL issue for this; Chisel doesn't generate the register so can't initialize it.

**Comment by zhemao** [comment]
Oh, right.
