### ISSUE TITLE
Define higher level chisel-testers API

### ISSUE THREAD

**Issue by ucbjrl** [ucb-bar/chisel3#231]
Currently, chisel-testers uses implementation details to interrogate the DUT graph. We need to provide a suitable API in chisel3.

See ucb-bar/chisel-testers#23

**Comment by ducky64** [comment]
Making more of the Chisel IR private (#414) as well as making Aggregate.getElements public may address parts of this issue. Will revisit after those changes are implemented.

**Comment by ducky64** [comment]
Duplicate sub-issue of #414
