### ISSUE TITLE
Fill(Chisel.UInt, Int) is in Chisel2, but not supported by Chisel3

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/chisel3#233]
In Chisel2 it looks like Fill() supports any ordering on the arguments. Chisel3 does not support Fill(Chisel.UInt, Int), which is a regression that is not checked for by the compatibility checker.

This breaks BOOM. If we don't support it fine, but it should be caught by the compatibility checker!

**Comment by aswaterman** [comment]
I think we shouldn't support it in chisel3, but that this should be added to the compatibility checker.

**Comment by ucbjrl** [comment]
Closed by ucb-bar/chisel#722
