### ISSUE TITLE
No Chisel3 compatibility warning for asInput()/asOutput() parenthesis issue

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/chisel3#239]
As demonstrated in this commit, Chisel3 no longer allows for `asInput()`, `asOutput()`. 

https://github.com/ucb-bar/riscv-boom/commit/b689ba35a1b904971105fe5f5f352040e558f0d3

It would be nice if this was caught in the compatibility checker.

**Comment by ducky64** [comment]
New API is to use Input(...), Output(...)
