### ISSUE TITLE
Deprecate either asUInt or asBits

### ISSUE THREAD

**Issue by colinschmidt** [ucb-bar/chisel3#269]
Right now they do they exact same thing. I don't see the purpose for this, and it might make the user think they actually do different things. (I checked the source code to check that they were equivalent)

For what its worth, rocket-chip never uses asBits...

**Comment by aswaterman** [comment]
asBits is nearly useless in practice, as it does the same thing as asUInt but returns a less concrete type.  I'd be fine with nuking it.  It wasn't in chisel2, so there's little compatibility concern.

**Comment by sdtwigg** [comment]
Definitely +1 on deprecating asBits.

It had a nice symmetry with fromBits (asBits and fromBits were nominally
inverses) but we can probably introduce an alias for fromBits that restores
this.

**Comment by ducky64** [comment]
Looks like this has been implemented, asBits is deprecated.
