### ISSUE TITLE
Wiring to a Clock produces invalid firrtl

### ISSUE THREAD

**Issue by ben-k** [ucb-bar/chisel3#272]
```
val my_clock = Clock()
my_clock := some_other_clock
```

This results in a node being referenced before it's defined in the generated firrtl.  It seems like the only valid way to use the Clock type right now is to hook it up at instantiation time.

**Comment by aswaterman** [comment]
I've never tried this before, but don't you need to write Wire(Clock())?

**Comment by jackkoenig** [comment]
I believe Andrew is right and this would also be caught by @sdtwigg's binding.

See #230

**Comment by ben-k** [comment]
Yup, the proposed fix works like a charm, thanks...
