### ISSUE TITLE
Not bound to synthesizable node?

### ISSUE THREAD

**Issue by donggyukim** [ucb-bar/chisel3#305]
I got an error with a previously working design as follows:

[info]   chisel3.core.Binding$BindingException: 'that' (chisel3.util.DecoupledIO@42f).bits: Not bound to synthesizable node, currently only Type description
[info]   at chisel3.core.Binding$.checkSynthesizable(Binding.scala:155)
[info]   at chisel3.core.Data.bulkConnect(Data.scala:142)
[info]   at chisel3.core.Data.$less$greater(Data.scala:170)
[info]   at strober.Channel.<init>(sim.scala:62)
[info]   at strober.SimUtils$$anonfun$genChannels$1$$anonfun$1.apply(util.scala:47)
[info]   at strober.SimUtils$$anonfun$genChannels$1$$anonfun$1.apply(util.scala:47)
[info]   at chisel3.core.Module$.do_apply(Module.scala:29)
[info]   at strober.SimUtils$$anonfun$genChannels$1.apply(util.scala:47)
[info]   at strober.SimUtils$$anonfun$genChannels$1.apply(util.scala:45)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)

What am I supposed to do to fix this?

**Comment by aswaterman** [comment]
If it previously emitted working FIRRTL, this is almost certainly a chisel3 bug.

**Comment by ucbjrl** [comment]
Does adding an:

    import chisel3.core.ExplicitCompileOptions.NotStrict

to the file sim.scala suppress the error?

**Comment by aswaterman** [comment]
er, right, I was assuming strober only used import Chisel._, not chisel3._.

**Comment by donggyukim** [comment]
It turns out that io definitions without `IO` can cause these wired errors. I think there should be warnings for not using it.

**Comment by aswaterman** [comment]
@donggyukim was that with chisel3 or Chisel?  In Chisel, IO is not supposed to be required, so it is a bug in Chisel if it issues the error.  If it was chisel3, you need IO.

**Comment by donggyukim** [comment]
It is with chisel3. Then, there should be errors without `IO`s.

**Comment by aswaterman** [comment]
ok cool

**Comment by aswaterman** [comment]
I assume issuing a warning is fundamentally difficult.  If it were easy to detect something was an IO without IO(), then I guess we wouldn't need IO()

**Comment by ucbjrl** [comment]
Right. We could improve the error message. In order to handle the Chisel2, IO-not-required case, we check to see if the unbound element is a component of the module's io. If so, we could issue a more useful error message.
