### ISSUE TITLE
Poor placement of EnqIO/DeqIO

### ISSUE THREAD

**Issue by ucbjrl** [ucb-bar/chisel3#308]
Currently, EnqIO and DeqIO are completely defined in the package objects (chisel3 and Chisel). This seems wrong and probably the source of at least one bug, since they differ.

These should be consolidated and moved to util/Decoupled.scala or deleted.

**Comment by aswaterman** [comment]
Alternatively, we could slay the beasts.

**Comment by ucbjrl** [comment]
Closed by #322
