### ISSUE TITLE
Compatibility mode can't handle Modules with reset/clock passed in

### ISSUE THREAD

**Issue by aswaterman** [ucb-bar/chisel3#310]
Instantiating this module in compatibility mode will trigger a binding error:

    class Test(reset: Bool) extends Module(_reset = reset) {
      val io = new Bundle {
        val done = Bool(OUTPUT)
      }

      io.done := Bool(false)
    }

Without the reset argument, it succeeds.

The same issue holds for passing in a clock.

**Comment by ucbjrl** [comment]
The class definition is picking up the implicit CompileOptions from materialize in chisel3.core, rather than the intended definition from the Chisel package object.
