### ISSUE TITLE
Range API

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/chisel3#330]
Just documenting what we talked about @ the firrtl meeting. Before firrtl range inference is done, I'd like to see some API that Chisel users can use to specify input ranges. Until range inference is done, this can be just some thin layer that converts ranges back to widths, but it'd be better than having the Chisel hardware designer write some range -> width conversion function that gets run everywhere [which is what I did a few years back] and having to swap that out down the line.

**Comment by ducky64** [comment]
Implemented in #369
