### ISSUE TITLE
deprecate single argument UInt/SInt factory method.

### ISSUE THREAD

**Issue by ucbjrl** [ucb-bar/chisel3#337]

**Comment by ccelio** [comment]
Is there any movement on this? Related: #294 .

**Comment by ucbjrl** [comment]
Awaiting review of updated code.

**Comment by ccelio** [comment]
Thanks @ucbjrl I somehow failed to notice PR #338.

**Comment by ducky64** [comment]
Fixed by #372 
Functionality remains without warning in Chisel._, but is deprecated (and planned to be removed soon) in chisel3._
