### ISSUE TITLE
Int.asUInt(Int) Doesn't Work

### ISSUE THREAD

**Issue by jackkoenig** [ucb-bar/chisel3#377]
```scala
class Test extends Module {
  val io = IO(new Bundle {
    val out = UInt(64.W)
  })
  io.out := 0.asUInt(64)
}
```

I forgot the `.W` on the width of the literal `0`, this just gives me a literal of width 1 instead of 64

```
circuit Test :
  module Test :
    input clock : Clock
    input reset : UInt<1>
    output io : {out : UInt<64>}

    io is invalid
    io is invalid
    io.out <= UInt<1>("h00") @[Test.scala 8:10]
```

Also, io is invalidated twice, perhaps a separate issue.

**Comment by ducky64** [comment]
I see the problem, it's interpreting it as a asUInt followed by a chained apply call. Looks like that's why we needed the empty parentheses in the function definition.
Fix coming in a few minutes.
