### ISSUE TITLE
in order try it needs fpga toolkit , but where ti buy?

### ISSUE THREAD

**Issue by Sandy4321** [ucb-bar/chisel3#382]
in order try it needs fpga toolkit , but where ti buy?

**Comment by Martoni** [comment]
Hello Sandy,
Personally I use an APF6_SP to develop with Chisel3.
The toolkit can be bought on the website : https://ssl3.ovh.net/~opossomcty/onlineshop/catalog/product_info.php?cPath=21_30&products_id=59&osCsid=c568ab58cf186b18aad715091ab79adb

**Comment by jackkoenig** [comment]
See above and https://github.com/ucb-bar/fpga-zynq/issues/28#issuecomment-262306661
