### ISSUE TITLE
Chisel Counter declaration is mixed up.

### ISSUE THREAD

**Issue by chick** [ucb-bar/chisel3#386]
Trying to import Counter in dsptools gives message
```
Warning:(6, 21) imported `Counter' is permanently hidden by definition of class Counter in package counters
import chisel3.util.Counter
```
Also seems impossible to declare the return type of function
```
import chisel3._
import util.chisel3.Counter
def getC: Counter = Counter(...)
```
There seems no way to get declaration of return value of getC and Counter.apply both correct
```
import util.chisel3.Counter
def getC = Counter(...)
```
but violates style guide

**Comment by jackkoenig** [comment]
I believe Counter is in package `chisel3.util`, so I think `import chisel3.util.Counter` should work.
