### ISSUE TITLE
Weird Width Decisions

### ISSUE THREAD

**Issue by jackkoenig** [ucb-bar/chisel3#388]
Consider:

```scala
class Literals extends Module {
  val io = IO(new Bundle {
    val out1 = Output(UInt(32.W))
    val out2 = Output(UInt(32.W))
  })

  io.out1 := "h_dead_beef".U
  io.out2 := "hdeadbeef".U

}
```

This results in the following Firrtl:

```
circuit Literals :
  module Literals :
    input clock : Clock
    input reset : UInt<1>
    output io : {out1 : UInt<32>, out2 : UInt<32>}

    io is invalid
    io is invalid
    io.out1 <= UInt<40>("h0deadbeef") @[Literals.scala 10:11]
    io.out2 <= UInt<32>("h0deadbeef") @[Literals.scala 11:11]
```

It looks like the underscores in "h_dead_beef" are contributing to the chosen width.

**Comment by aswaterman** [comment]
......oops

**Comment by jackkoenig** [comment]
Related: "h0a".U should have a width of 4 right? "h1a".U should have a width of 5?

**Comment by aswaterman** [comment]
5 is probably the best value. I would just handle this by parsing as a BigInt and calling bitLength.

**Comment by jackkoenig** [comment]
That was my plan, what about for signed though? .bitLength + 1?

**Comment by jackkoenig** [comment]
Just kidding, can't do .S on Strings

**Comment by mwachs5** [comment]
Why is 5 better for 0a than 8?

**Comment by aswaterman** [comment]
I think either is justifiable. My argument for the smaller value is that
there's no difference between writing 0xa.U and 0x0a.U, so "a".U and "0a".U
should also be the same as each other. But I could be convinced otherwise.

**Comment by mwachs5** [comment]
Sure, I agree with that. I thought you were saying 0a could be inferred to
width 5.

**Comment by aswaterman** [comment]
My bad, I meant 0a should be 4 bits and 1a should be 5 bits
