### ISSUE TITLE
Compatibility layer interoperability

### ISSUE THREAD

**Issue by jackkoenig** [ucb-bar/chisel3#410]
While it requires changes to a different repo, I think this should be tracked with the 3.0.0 milestone.

To ensure that the compatibility layer properly interoperates with chisel3._, we need real code to be using it so we should have some files of rocket-chip (or another large project) using both packages.

**Comment by jackkoenig** [comment]
This is done in ucb-bar/testchipip, see https://github.com/ucb-bar/testchipip/blob/master/src/main/scala/Util.scala

**Comment by ben-k** [comment]
Wow, I feel so important!
