### ISSUE TITLE
Are `EnqIO` and `DeqIO` backwards?

### ISSUE THREAD

**Issue by albert-magyar** [ucb-bar/chisel3#437]
I see that `EnqIO` is used on the _output_ of `Queue` and vice-versa. Is this intentional? Chisel2 did not use `EnqIO` or `DeqIO` in `Queue` at all (as far as I can tell).

https://github.com/ucb-bar/chisel3/blob/3215df07a97b58babb1deb3fab0928198b1daad2/src/main/scala/chisel3/util/Decoupled.scala#L131-L146

**Comment by aswaterman** [comment]
I thought we were removing them altogether: https://github.com/ucb-bar/chisel3/pull/322

**Comment by albert-magyar** [comment]
That would make even more sense. @ucbjrl, is there a reason #322 was reverted?

**Comment by ucbjrl** [comment]
According to the commit comment:

"Update chisel-testers before commiting this change (deleting EnqIO/DeqIO)."

**Comment by ucbjrl** [comment]
W.r.t. the apparent reversal of EnqIO/DeqIO, I believe I managed to convince myself that inside the Queue, they are inverse of what the client sees from outside (if that makes sense).

**Comment by aswaterman** [comment]
Ah, I see.  Removing them still strikes me as the right thing to do.  This conversation (and Stephen's decision to change them) is compelling evidence that they are confusing, because whether they are named correctly is context/orientation-dependent.  I don't know what the chisel-testers dependence was referring to, but hopefully that change is just a search and replace job.  @chick ?

**Comment by jackkoenig** [comment]
When I first ran into them I had the same confusion as Albert. I'm inclined
to agree that they're more trouble than they're worth.

**Comment by ucbjrl** [comment]
I started the replacement, then realized I was basically replacing EnqIO/DeqIO with EnqIO/DeqIO and gave up. There is obviously a use case for them. @chick and I will discuss the issue.

**Comment by ucbjrl** [comment]
I think one source of confusion is the comment for ReadyValid:

```
/** An I/O Bundle containing 'valid' and 'ready' signals that handshake
  * the transfer of data stored in the 'bits' subfield.
  * The base protocol implied by the directionality is that the consumer
  * uses the flipped interface. Actual semantics of ready/valid are
  * enforced via use of concrete subclasses.
  */
abstract class ReadyValidIO[+T <: Data](gen: T) extends Bundle
{
  val ready = Input(Bool())
  val valid = Output(Bool())
  val bits  = Output(gen.chiselCloneType)
}
```

It sure looks to me that this interface is defined from the perspective of the consumer (`bits` are `Output`). I think the comment should be inverted:

```
  * The base protocol implied by the directionality is that the producer
  * uses the flipped interface. Actual semantics of ready/valid are
```

**Comment by mwachs5** [comment]
What? Wouldn't the consumer have the bits as input? For your Queue case your confusion may be justified, but ReadyValidIO and the comments seem just fine in the general case.

I was taught that interfaces should be conventionally defined in the "master" way, and "slave" uses flipped version. The current ReadyValidIO code and comments above seems consistent with that...

**Comment by ucbjrl** [comment]
You are correct. My confusion stems from the fact that the interface is defined from the point of view of something the consumer can use (consume). So of course, something providing a ReadyValid interface for the consumer, must present `bits` as `Output` so the consumer can connect them to the appropriate `Input` in their circuit.

I retract my suggestion to invert the comment.

**Comment by edwardcwang** [comment]
What about a comment along the lines of "the producer uses the interface as-is (outputs bits) while the consumer uses the flipped interface (input bits)" to fully clarify the confusion?

**Comment by ducky64** [comment]
Solution: make Decoupled and queues use DecoupledIOs, and clean up everything that uses it like chisel-testers. Unlikely to break rocket-chip.
