### ISSUE TITLE
Document which way Bundles are packed

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/chisel3#441]
When turning Bundles into UInt, and vice versa, I always forget which way they are packed (what is the endianness basically). Is this documented somewhere? I would add it to the Cookbook item related to converting between Bundles and UInt, but not sure how to suggest edits to the Wiki.

**Comment by jackkoenig** [comment]
I'm working on this as suggested on https://github.com/ucb-bar/chisel3/pull/366#discussion_r91828211.

For the Cookbook, working examples added [here](https://github.com/ucb-bar/chisel3/tree/master/src/test/scala/cookbook) are appreciated. I'm also working on a mirrored Github repo of the wiki to allow PRs against it directly.

**Comment by mwachs5** [comment]
Ah, I guess I should have just looked at the examples more closely. Thx
