### ISSUE TITLE
Iterable or Seq

### ISSUE THREAD

**Issue by ducky64** [ucb-bar/chisel3#449]
We have uses of both (and a few instances of IndexedSeq, for kicks and giggles) spread across our codebase and API. We should standardize on one.

**Comment by aswaterman** [comment]
I don't think so.  They have different contracts.  Iterable makes sense to use when the traversal order doesn't affect semantics; Seq makes sense when it does.  It's actually good self-documentation.

Mux1H's overloads correctly use Iterable in one case and Seq in the others.

**Comment by aswaterman** [comment]
I can see the argument for replacing the few uses of IndexedSeq with Seq.

**Comment by ducky64** [comment]
Resolution: each has their own contract and we're going with least-specific class. May consider individual instances that don't make sense.
