### ISSUE TITLE
SeqMem Clks

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/chisel3#457]
Just double checking, since it doesn't seem to be anywhere in Chisel3. Although FIRRTL supports SeqMem's having multiple clks, Chisel *still* doesn't? Is it just because this hasn't been urgent? Also, I haven't tried yet, but I assume changing the Module clk would change both the read and write clocks to not use the default 'clock'?

**Comment by ben-k** [comment]
I believe you are correct on both counts.

**Comment by aswaterman** [comment]
The goal is for the forthcoming withClockAndReset construct to govern the clock inherited by a port declaration, rather than associating a clock with the memory itself.

**Comment by ben-k** [comment]
Agreed, but is there a vision for how this would work with distinct read and write clocks for a SeqMem?

**Comment by aswaterman** [comment]
Yeah, that's what I mean.  You declare the Mem outside, then put the ports inside two different withClockAndReset blocks.

**Comment by ducky64** [comment]
Should be fixed by withClockAndReset
