### ISSUE TITLE
Default Value for Valid IO

### ISSUE THREAD

**Issue by preyas3359** [ucb-bar/chisel3#459]
Hi All,

What is the default value for valid signal in ValidIO?
While testing a design, I am seeing tester picking up any of 1 and 0. 

Do we need to assign default value for valid signal?

Regards,
Preyas

**Comment by ducky64** [comment]
Currently unconnected lines are randomized, which probably explains what you're seeing.

There's a proposal that will have the compiler detect unconnected lines not explicitly marked as not-connected and error on those, but that's not implemented yet.

**Comment by ducky64** [comment]
Superseded by #413
