### ISSUE TITLE
Inheritance Diagram For Chisel Types

### ISSUE THREAD

**Issue by mwachs5** [ucb-bar/chisel3#463]
I remember in the past when learning Chisel there was a nice diagram with all the different data types and how they inherit / are related. I don't recall where I saw it.

 Does this diagram still exist? Can someone point me to it?

**Comment by jackkoenig** [comment]
There's a small on in the README: https://github.com/ucb-bar/chisel3#data-types-overview
I also think https://github.com/ucb-bar/chisel3/pull/432 (which I need to merge, whoops) adds some automatically generated diagrams to the ScalaDoc

**Comment by mwachs5** [comment]
Gracias.
