### ISSUE TITLE
do_abs for fixed pt

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/chisel3#466]
Currently you have
```
def do_abs(implicit sourceInfo: SourceInfo): UInt = {
    Mux(this < FixedPoint.fromBigInt(0), (FixedPoint.fromBigInt(0)-this).asUInt, this.asUInt)
  }
```

I really think do_abs should return type T. It's confusing when the absolute value of a potentially non-integer fixed point # returns a UInt as opposed to a UFix (or just Fixed). 

Or call it abs_int for clarity...

**Comment by chick** [comment]
@shunshou seems like it's return type should be a FixedPoint.  Not doing so loses information.  I don't see any reason to make it a T.

**Comment by shunshou** [comment]
Sorry I mean in general for Sint too. Just make it the same type as the input.

**Comment by chick** [comment]
@ducky64 @ucbjrl I think @shunshou is right, this is a minor API issue but it seems like the current implementation is incorrect.  There seem to be very few uses of these methods, I am happy to do it if you agree

**Comment by ucbjrl** [comment]
I concur.

**Comment by shunshou** [comment]
It's only incorrect for fixed, but it would make sense to be consistent across the different data types.
