### ISSUE TITLE
remove import chisel3.core.ExplicitCompileOptions.NotStrict

### ISSUE THREAD

**Issue by ucbjrl** [ucb-bar/chisel3#492]
There is a:
```
// TODO: remove this once we have CompileOptions threaded through the macro system.
import chisel3.core.ExplicitCompileOptions.NotStrict
```
in 7 chisel files.
Is it time?

I'd like to replace the following in QueueIO:
```
  val enq = DeqIO(gen)
  val deq = EnqIO(gen))
```
with
```
  val enq = Flipped(EnqIO(gen))
  val deq = Flipped(DeqIO(gen))
```
to help reduce some of the confusion, but the NotStrict compile options introduce a connection error when cloneChiselType() fails to preserver directionality (due to 09282f3).

**Comment by ducky64** [comment]
If it works, and after we merge #476 (to make sure that when you remove it, it's not just materializing Strict)

**Comment by jackkoenig** [comment]
Fixing #495 might be required for this since people will likely use utils but pass bundles defined in Chisel._
