### ISSUE TITLE
Cheatsheet switch statement

### ISSUE THREAD

**Issue by jchang0** [ucb-bar/chisel3#506]
By experimentation, it looks like the for the switch-is statement, the is statement must be on a different line than the closing brace of the previous is statement

e.g. this as written on the cheetsheet does not work: (it gives this compilation error message:
overloaded method value apply with alternatives:   (x: chisel3.core.UInt)chisel3.core.Bool <and>   (x: Int)chisel3.core.Bool <and>   (x: BigInt)chisel3.core.Bool  cannot be applied to (Unit))

```scala
switch(x) {
  is(value1) {
    // run if x === value1
  } is (value2) {
    // run if x === value2
  }
}
```

But if I put the is statement on a different line, it works:

```scala
switch(x) {
  is(value1) {
    // run if x === value1
  }
  is (value2) {
    // run if x === value2
  }
}
```

Not sure if it's documentation error or chisel3 issue.

**Comment by ducky64** [comment]
It looks like the first is just tripping up the Scala parser.

One attempt to solve it would be allowing `is`s to chain, parsing as `is (value1) {block1} .is (value2) {block2}`. However, that ends up in the same situation as `when` and `.elsewhen`, where if you omit the explicit dot, Scala parses `block2` as an argument for `value2`.

Will update the cheatsheet, this is bad.

**Comment by ducky64** [comment]
Cheatsheet source updated.
@chick or @ucbjrl, can one of you update the compiled version on the website?

**Comment by chick** [comment]
@ducky64 website updated
