### ISSUE TITLE
Have an options where Asserts are not filtered with reset

### ISSUE THREAD

**Issue by jchang0** [ucb-bar/chisel3#521]
Currently, the assertions are disabled when reset is on.

This is an issue when I want the assertions itself to explicitly consider the reset behavior (or have the assertions be based on reset behavior).

Would like to have a feature where I can deviate from default behavior and not have it generate the reset filter automatically for some assertions.

**Comment by aswaterman** [comment]
Can we do this by writing: withReset (Bool(false)) { /* put the assertion here */ }

**Comment by jackkoenig** [comment]
I think that should work

**Comment by jackkoenig** [comment]
Keep in mind that Firrtl also guards assertions with `PRINTF_COND` which is usually set by the build system to guard assertions with the top-level reset.

**Comment by azidar** [comment]
Will close this issue now, but please reopen if the proposed solution is unacceptable.
