### ISSUE TITLE
getResources Bug

### ISSUE THREAD

**Issue by shunshou** [ucb-bar/chisel3#549]
I'm trying to port over some of my previous work from Chisel2 to Chisel3. I was hoping to have one project depending on both Chisel2 and Chisel3 so I could incrementally port some stuff over (not running both at the same time). I ran into a really nasty issue when trying to get Verilator tests to work where (chisel-testers) VerilatorBackend's getResources (or w/e it's called) was pulling in the sim_api.h from chisel2 instead of the sim_api.h in chisel-testers. 

If your top-level project depends on multiple sbt-projects whose src/main/resource directory contains files of the same name, it's painful to figure out how to get the precedence to be right. 

The directory structure should be src/main/resource/package_name or something to disambiguate and all of your getResourceAsStream args should reflect the package_name. i.e. /packageName/file

I know this doesn't immediately affect 99% of users, but wasting time debugging this without understanding how Scala/sbt works can be a huge time sink, so please fix this!

**Comment by ucbjrl** [comment]
This is related to ucb-bar/firrtl#398 (which is still waiting for review).

**Comment by shunshou** [comment]
@ucbjrl how can we move this along so other people don't run into weird problems?

**Comment by ucbjrl** [comment]
I propose we ensure resources are explicitly scoped in ucb-bar jars - there should be a top-level resource directory with the name of the project/jar - i.e., firrtl resources should live in `src/{main,test}/resources/firrtl/...`, chisel2 resources in `src/{main,test}/resources/chisel2/...` etc. We can discuss this at the next chisel meeting.

**Comment by chick** [comment]
added this to chisel action items
