### ISSUE TITLE
withClock and friends doesn't apply to child modules correctly

### ISSUE THREAD

**Issue by grebe** [ucb-bar/chisel3#567]
In a module I essentially have the following

```
withClockAndReset(clock = newClock, reset = newReset) {
  val mod = Module(new ModuleOfSomeVariety)
  ...
}
```

and the module doesn't get newClock or newReset. According to @ducky64, setupInParent gets the parents clock whereas withClockAndReset only modifies the Builder's clock.

**Comment by jackkoenig** [comment]
How embarrassing. I've PRed a fix

**Comment by shunshou** [comment]
Hm I think this is sort of what I was trying to get at a couple of nights ago. It only worked w/ registers. Either way, I find this to be a little confusing...

**Comment by jackkoenig** [comment]
@shunshou Yeah I definitely misunderstood you. What do you find confusing about the actual intended behavior?

```scala
val inst = Module(new MyModule)
inst.clock := someClock
inst.reset := someReset
// is replaced by
val inst = withClockAndRest(someClock, someReset) { Module(new MyModule) }
```

**Comment by grebe** [comment]
Thanks so much @jackkoenig, you da real mvp

**Comment by shunshou** [comment]
Like idk... to some extent, I think if you're overriding module clocks, doing the override_clock thing seems more explicit. Vs. if you wanted to override clks of individual registers, you'd consider using withClockAndReset. As you said, similar functionality, different implementation... but it'd be nice to make it clear exactly what the difference in implementation is.
