### ISSUE TITLE
Potential backwards-incompatible [for rocket-chip] changes to be made in Chisel3

### ISSUE THREAD

**Issue by hcook** [ucb-bar/chisel3#6]
- [ ] package Chisel => package chisel
- [ ] chiselMain => Driver.elaborate (with no wrapping of top level module) 
- [ ] trait FileSystemUtilities => object FileUtils
- [ ] remove Module and Bundle factory methods that apply new params as partial functions => paramsScope

**Comment by chick** [comment]
@hcook does this need to be open still?

**Comment by ducky64** [comment]
Rocket-chip will stay on the compatibility layer.

We are no longer planning to rename chisel3 -> chisel, and Chisel will remain as the compatibility package.
